selector:
  type: ['PosteriorBasedSelector']
  model_name: 'Self-Supervision'
  model_config_path: 'InnerEyeDataQuality/configs/models/benchmark_3_idn/b3_ssl_cleaning_v2.yaml'
  output_directory: 'b3_ssl_cleaning_v2'
tensorboard:
  save_events: False
