selector:
  type: ['PosteriorBasedSelectorJoint']
  model_name: 'Coteaching-Active'
  model_config_path: 'InnerEyeDataQuality/configs/models/cifar10h_noise_30/resnet_co_teaching.yaml'
  use_active_relabelling: True

