name: PR-$(Date:yyyyMMdd)$(Rev:-r)
variables:
  model: 'BasicModel2Epochs'
  is_train: 'True'
  more_switches: '--log_level=DEBUG'
  run_recovery_id: ''
  tags: 'PR'
  user_friendly_name: 'PR build'
  number_of_cross_validation_splits: 0

jobs:
  - job: Linux
    pool:
      vmImage: 'ubuntu-18.04'
    steps:
      - template: build.yaml