device: cuda:3
cudnn:
  benchmark: True
  deterministic: True
dataset:
  name: NoisyChestXray
  dataset_dir: /datadrive/rsna_train
  n_channels: 3
  n_classes: 2
  cxr_consolidation_noise_rate: 0.10
model:
  type: cxr
  name: resnet50
train:
  use_balanced_sampler: True
  pretrained: False
  seed: 5
  batch_size: 32
  optimizer: adam
  base_lr: 1e-5
  output_dir: cxr/nih10/co_teaching
  log_period: 5
  checkpoint_period: 20
  use_co_teaching: True
  use_teacher_model: False
  co_teaching_consistency_loss: False
  co_teaching_use_graph: False
  co_teaching_forget_rate: 0.15
  co_teaching_num_gradual: 0
  co_teaching_num_warmup: 20
  dataloader:
    num_workers: 6
    drop_last: False
    pin_memory: False
validation:
  batch_size: 16
  dataloader:
    num_workers: 6
    drop_last: False
    pin_memory: False
preprocess:
  center_crop_size: 224
  resize: 256
scheduler:
  epochs: 150
  type: constant
augmentation:
  use_random_horizontal_flip: True
  use_random_affine: True
  use_random_color: True
  use_random_crop: True
  use_gamma_transform: False
  use_random_erasing: False
  add_gaussian_noise: False
  random_horizontal_flip:
    prob: 0.5
  random_affine:
    max_angle: 30
    max_horizontal_shift: 0.00
    max_vertical_shift: 0.00
    max_shear: 15
  random_color:
    brightness: 0.2
    contrast: 0.2
    saturation: 0.0
  random_crop:
      scale: (0.8, 1.0)
