device: cuda
cudnn:
  benchmark: True
  deterministic: True
dataset:
  name: CIFAR10H
  noise_temperature: 10.0
  num_samples: 5000
model:
  type: cifar
  name: resnet
  init_mode: kaiming_fan_out
  resnet:
    depth: 110
    initial_channels: 16
    block_type: basic
    apply_l2_norm: True
train:
  resume_epoch: 0
  seed: 1
  batch_size: 256
  optimizer: sgd
  base_lr: 0.1
  momentum: 0.9
  nesterov: True
  weight_decay: 1e-4
  output_dir: experiments/cifar10h_noise_30/co_teaching
  log_period: 100
  checkpoint_period: 100
  use_co_teaching: True
  co_teaching_forget_rate: 0.28
  co_teaching_num_gradual: 10
  dataloader:
    num_workers: 2
    drop_last: False
    pin_memory: False
validation:
  batch_size: 2048
  dataloader:
    num_workers: 2
    drop_last: False
    pin_memory: False
test:
  batch_size: 128
  dataloader:
    num_workers: 2
    pin_memory: False
scheduler:
  epochs: 160
  type: multistep
  milestones: [80, 120]
  lr_decay: 0.1
augmentation:
  use_random_horizontal_flip: True
  use_label_smoothing: False
  use_random_affine: True
  use_random_color: True
  random_horizontal_flip:
    prob: 0.5
  random_affine:
    max_angle: 15
    max_horizontal_shift: 0.05
    max_vertical_shift: 0.05
    max_shear: 5
  random_color:
    brightness: 0.5
    contrast: 0.5
    saturation: 0.5

  
  
  



