dataset:
  name: CIFAR10H
  num_workers: 6
train:
  seed: 1
  batch_size: 512
  base_lr: 1e-3
  output_dir: cifar10h/self_supervised
  resume_from_last_checkpoint: False
  self_supervision:
    type: byol
    encoder_name: resnet50
scheduler:
  epochs: 2500
preprocess:
  resize: 32
