name: 'Check pull request title'
on:
  pull_request:
    types: [edited, opened, synchronize, reopened]

jobs:
  title-check:
    runs-on: ubuntu-latest
    if: ${{ github.event.pull_request.user.login != 'dependabot[bot]' }}
    steps:
      - uses: naveenk1223/action-pr-title@master
        with:
          regex: '^[A-Z]+\:\s[A-Z].+[^\.]$'  # Regex the title should match.
          allowed_prefixes: 'ENH,BUG,STYLE,DOC,DEL'  # title should start with the given prefix
          prefix_case_sensitive: true  # title prefixes are case ensitive
          min_length: 10  # Min length of the title
          max_length: 72  # Max length of the title
