steps:
  - template: checkout.yml

  - template: prepare_conda.yml

  - template: store_settings.yml

  # https://docs.microsoft.com/en-us/azure/devops/pipelines/release/caching?view=azure-devops#pythonanaconda
  - task: Cache@2
    displayName: Use cached Conda environment AzureML_SDK
    inputs:
      # Beware of changing the cache key or path independently, safest to change in sync
      key: 'usr_share_miniconda_azureml_conda | "$(Agent.OS)" | azure-pipelines/azureml-conda.yml'
      path: /usr/share/miniconda/envs
      cacheHitVar: CONDA_CACHE_RESTORED

  - script: conda env create --file azure-pipelines/azureml-conda.yml
    displayName: Create Conda environment AzureML_SDK
    condition: eq(variables.CONDA_CACHE_RESTORED, 'false')

  - script: source activate AzureML_SDK
    displayName: Check if Conda environment AzureML_SDK is present
