steps:
  - template: checkout.yml

  - template: store_settings.yml

  - bash: |
      conda env create --file environment.yml --name AzureRunner
      pip freeze
    failOnStderr: false
    displayName: Create full conda environment and print package list
