# schedules:
# - cron: "0 0 * * *"
#   displayName: Daily midnight regression tests
#   branches:
#     include:
#     - phessey/improve-regression-tests

pr:
  branches:
    include:
    - '*'

name: RegressionTests-$(Date:yyyyMMdd)$(Rev:-r)
variables:
  more_switches: '--log_level=DEBUG --pl_deterministic'
  run_recovery_id: ''
  tag: ''
  train: True
  number_of_cross_validation_splits: 0
  cluster: 'training-nc12'
  # Disable a spurious warning
  # https://stackoverflow.com/questions/56859264/publishing-code-coverage-results-from-reportgenerator-not-working
  disable.coverage.autogenerate: 'true'

jobs:
  - job: LungRegression
    variables:
      - name: model
        value: 'LungRegression'
      - name: tag
        value: 'TrainLungRegressionModel'
      - name: more_switches
        value: '--log_level=DEBUG --pl_deterministic --use_dataset_mount=True --regression_test_folder=RegressionTestResults/LungRegression --regression_test_csv_tolerance=0.005'
    pool:
      vmImage: 'ubuntu-20.04'
    env:
      SUBSCRIPTION_ID: $(InnerEyeDevSubscriptionID)
      APPLICATION_ID: $(InnerEyeDeepLearningServicePrincipalID)
      APPLICATION_KEY: $(InnerEyeDeepLearningServicePrincipalKey)
      BRANCH: $(Build.SourceBranch)
    steps:
      - template: train_template.yml
        parameters:
          wait_for_completion: 'True'
          max_run_duration: '30m'
